### ISSUE TITLE
[Question] Wrong foreign key reference?

### ISSUE THREAD

**Issue by RobertLemmens** [cdiniz/slick-akka-http-oauth2#2]
Question about the following part. Why does the oauth_access_token_client_fk has the Authorization code table as reference?

 def oauthClient = foreignKey(
      "oauth_access_token_client_fk",
      oauthClientId,
      OauthAuthorizationCodeTableQ)(_.id)

**Comment by cdiniz** [comment]
Hi Robert, I will update this repo to use slick-repo as I did in https://github.com/cdiniz/slick-akka-http. I'll review the Fk after.

**Comment by RobertLemmens** [comment]
I see. Looking forward to the result. Great work.

**Comment by cdiniz** [comment]
Hi Robert, thanks for your input. I wont have time to update this repo in next days, so I fixed the fk reference. many thanks for your input.
